<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Lex.V3.Custody.Azure</RootNamespace>
    <AssemblyName>Lex.V3.Custody.Azure</AssemblyName>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Lex.V3.Contracts/Lex.V3.Contracts.csproj" />
  </ItemGroup>
</Project>
