<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Lex.Law\Lex.Law.csproj" />
    <EmbeddedResource Include="eu-scope.json" LogicalName="Lex.Sources.EurLex.eu-scope.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
