using Lex.V3.TestSupport;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Lex.V3.Tests.Census;

/// <summary>
/// Every type in the swept assemblies whose declared constructors are all non-public, with the
/// members that can hand one out. 128 of them when this was written.
/// </summary>
/// <remarks>
/// <para>
/// A type with no public constructor is a type whose author decided callers must come through a
/// named door, and the value of that decision is exactly the number of doors. The per-type pins
/// built on <see cref="ConstructionSurface.Of"/> state that number exactly for the types somebody
/// remembered to guard. This states it for all of them, so a type that nobody remembered is inside
/// a pin rather than outside every pin, and a second factory added anywhere in the assembly fails
/// this test.
/// </para>
/// <para>
/// Why it is a sweep. <see cref="ClosedSurfaceCensus"/> selects on the type declaring at least one
/// constructor and none of them public. That is a property of the type, so a new guarded type
/// appears here on its own, and a type that gains a public constructor drops out of the list and
/// fails the pin rather than silently leaving the census. Neither the selection nor the rendering
/// consults the expected answer below.
/// </para>
/// <para>
/// What it does not do, stated so nobody cites it for more than it checks. Each door is the
/// construction surface's own entry with the parameter list and return type cut off, so an existing
/// door changing its parameters passes here; the exact per-type pins catch that where they exist,
/// and where they do not that gap is real. Holders are excluded, so a field or property that
/// carries the type is not a line here. Doors the compiler generated for lambdas are counted rather
/// than named, because their mangled ordinals move when an unrelated method is added above them,
/// and a pin that fires on edits that opened no door is a pin people learn to regenerate without
/// reading.
/// </para>
/// </remarks>
[TestClass]
public sealed class GuardedConstructionCensusTests
{
    [TestMethod]
    public void EveryConstructionRestrictedTypeInTheSweptAssembliesHasExactlyTheseDoors()
    {
        CollectionAssert.AreEqual(
            new[]
            {
                "Lex.V3.Api.SyntheticApiState: constructor private instance "
                    + "Lex.V3.Api.SyntheticApiState::.ctor, "
                    + "constructor private static Lex.V3.Api.SyntheticApiState::.cctor, "
                    + "method public static Lex.V3.Api.SyntheticApiBootstrap::OpenAsync, "
                    + "method public static Lex.V3.Api.SyntheticApiState::Available",
                "Lex.V3.Api.SyntheticIndexResolver: constructor private instance "
                    + "Lex.V3.Api.SyntheticIndexResolver::.ctor, "
                    + "method public static Lex.V3.Api.SyntheticIndexResolver::Open",
                "Lex.V3.Artifacts.ArtifactAdmissionFailure: by-ref-method public instance "
                    + "Lex.V3.Artifacts.HeaderReadResult::Deconstruct, "
                    + "constructor internal instance "
                    + "Lex.V3.Artifacts.ArtifactAdmissionFailure::.ctor, "
                    + "method private static Lex.V3.Artifacts.AdmissionHeaderReader::Failure, "
                    + "method private static Lex.V3.Artifacts.AdmissionHeaderReader::Scan",
                "Lex.V3.Artifacts.ArtifactAdmissionInspection: constructor internal instance "
                    + "Lex.V3.Artifacts.ArtifactAdmissionInspection::.ctor, "
                    + "method private static Lex.V3.Artifacts.ProductionArtifactAdmission::Rejected, "
                    + "method public instance "
                    + "Lex.V3.Artifacts.ProductionArtifactAdmission::InspectAsync",
                "Lex.V3.Artifacts.PreviewArtifactVerification: constructor private instance "
                    + "Lex.V3.Artifacts.PreviewArtifactVerification::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Artifacts.PreviewArtifactVerification::Accepted, "
                    + "method internal static "
                    + "Lex.V3.Artifacts.PreviewArtifactVerification::Rejected, "
                    + "method private static Lex.V3.Artifacts.PreviewArtifactVerifier::Rejected, "
                    + "method public instance Lex.V3.Artifacts.PreviewArtifactVerifier::VerifyAsync",
                "Lex.V3.Artifacts.PreviewArtifactVerifier: constructor private instance "
                    + "Lex.V3.Artifacts.PreviewArtifactVerifier::.ctor, "
                    + "method public static "
                    + "Lex.V3.Artifacts.PreviewArtifactVerifier::CreateStageZero",
                "Lex.V3.Artifacts.ProductionArtifactAdmission: constructor private instance "
                    + "Lex.V3.Artifacts.ProductionArtifactAdmission::.ctor, "
                    + "method public static "
                    + "Lex.V3.Artifacts.ProductionArtifactAdmission::CreateStageZero",
                "Lex.V3.Artifacts.StrictPayloadReader+ContainerFrame: constructor private instance "
                    + "Lex.V3.Artifacts.StrictPayloadReader+ContainerFrame::.ctor, "
                    + "method public static "
                    + "Lex.V3.Artifacts.StrictPayloadReader+ContainerFrame::Array, "
                    + "method public static "
                    + "Lex.V3.Artifacts.StrictPayloadReader+ContainerFrame::Object",
                "Lex.V3.Artifacts.SyntheticDerivationException: base-constructor protected "
                    + "instance System.Exception::.ctor, "
                    + "base-constructor public instance System.Exception::.ctor, "
                    + "base-constructor public instance System.Exception::.ctor, "
                    + "base-constructor public instance System.Exception::.ctor, "
                    + "constructor internal instance "
                    + "Lex.V3.Artifacts.SyntheticDerivationException::.ctor",
                "Lex.V3.Artifacts.SyntheticSliceVerification: by-ref-method public instance "
                    + "Lex.V3.Artifacts.SyntheticSliceArtifactVerifier+BlobRead::Deconstruct, "
                    + "constructor private instance "
                    + "Lex.V3.Artifacts.SyntheticSliceVerification::.ctor, "
                    + "method internal static Lex.V3.Artifacts.SyntheticSliceVerification::Accepted, "
                    + "method internal static Lex.V3.Artifacts.SyntheticSliceVerification::Rejected, "
                    + "method private instance "
                    + "Lex.V3.Artifacts.SyntheticSliceArtifactVerifier::ValidateManifest, "
                    + "method private static "
                    + "Lex.V3.Artifacts.SyntheticSliceArtifactVerifier::Rejected, "
                    + "method public instance "
                    + "Lex.V3.Artifacts.SyntheticSliceArtifactVerifier::VerifyAsync",
                "Lex.V3.Contracts.EuPlainLiteralDriftProbePlan: constructor internal instance "
                    + "Lex.V3.Contracts.EuPlainLiteralDriftProbePlan::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.EuPlainLiteralDriftProbePlan::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.EuPlainLiteralDriftProbePlan::<Clone>$",
                "Lex.V3.Contracts.EuSeedResolutionBatch: constructor internal instance "
                    + "Lex.V3.Contracts.EuSeedResolutionBatch::.ctor, "
                    + "constructor private instance Lex.V3.Contracts.EuSeedResolutionBatch::.ctor, "
                    + "method private static Lex.V3.Contracts.EuSeedResolutionPlan::CreateBatch, "
                    + "method public instance Lex.V3.Contracts.EuSeedResolutionBatch::<Clone>$",
                "Lex.V3.Contracts.EuSeedResolutionRow: constructor internal instance "
                    + "Lex.V3.Contracts.EuSeedResolutionRow::.ctor, "
                    + "constructor private instance Lex.V3.Contracts.EuSeedResolutionRow::.ctor, "
                    + "method public instance Lex.V3.Contracts.EuSeedResolutionRow::<Clone>$, "
                    + "1 compiler-generated",
                "Lex.V3.Contracts.Source.Absence.AbsenceComparisonPolicy: constructor private "
                    + "instance Lex.V3.Contracts.Source.Absence.AbsenceComparisonPolicy::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceComparisonPolicy::TryCreate",
                "Lex.V3.Contracts.Source.Absence.AbsenceCut: constructor private instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceCut::.ctor, "
                    + "method private static Lex.V3.Contracts.Source.Absence.AbsenceCut::Create, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceCut::TryCreateComplete, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceCut::TryCreatePartial",
                "Lex.V3.Contracts.Source.Absence.AbsenceFamilyEnumerationProof: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceFamilyEnumerationProof::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationDeliveryReceipt::TryProveFam"
                    + "ilyEnumeration, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceFamilyEnumerationProof::TryCreate",
                "Lex.V3.Contracts.Source.Absence.AbsenceFamilyObservation: constructor private "
                    + "instance Lex.V3.Contracts.Source.Absence.AbsenceFamilyObservation::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceFamilyObservation::TryCreate",
                "Lex.V3.Contracts.Source.Absence.AbsenceHistoryGenerationId: constructor private "
                    + "instance Lex.V3.Contracts.Source.Absence.AbsenceHistoryGenerationId::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceHistoryGenerationId::TryCreate",
                "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger: constructor private "
                    + "instance Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger::TryOpen",
                "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger+CutReceipt: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger+CutReceipt::.ctor, "
                    + "method private instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger::LastAdvancingReceipt, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger::TryAppend",
                "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger+Generation: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger+Generation::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger+Generation::Open, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceHistoryLedger::TryTransitionCompariso"
                    + "nPolicy",
                "Lex.V3.Contracts.Source.Absence.AbsenceReplacementClassification: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceReplacementClassification::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceReplacementClassification::TryClassif"
                    + "y",
                "Lex.V3.Contracts.Source.Absence.AbsenceReplacementCoordinateProfile: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceReplacementCoordinateProfile::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceReplacementCoordinateProfile::TryCrea"
                    + "te",
                "Lex.V3.Contracts.Source.Absence.AbsenceSubject: constructor private instance "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceSubject::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Absence.AbsenceSubject::TryCreate",
                "Lex.V3.Contracts.Source.Core.BoundMachineRequestIdentity: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Core.BoundMachineRequestIdentity::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryBinder::OpenIdentity",
                "Lex.V3.Contracts.Source.Core.CutReleaseGate: constructor private instance "
                    + "Lex.V3.Contracts.Source.Core.CutReleaseGate::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.CutReleaseGate::TryEvaluate",
                "Lex.V3.Contracts.Source.Core.EnumerationDeliveryComparison: constructor private "
                    + "instance Lex.V3.Contracts.Source.Core.EnumerationDeliveryComparison::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationDeliveryReceipt::RequireFloo"
                    + "redRun, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.EnumerationDeliveryComparison::Create",
                "Lex.V3.Contracts.Source.Core.GlobalBlockerCountVector: constructor private "
                    + "instance Lex.V3.Contracts.Source.Core.GlobalBlockerCountVector::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.GlobalBlockerCountVector::Recompute",
                "Lex.V3.Contracts.Source.Core.MachineQueryBinder+MintedBoundMachineRequest: "
                    + "base-constructor private-protected instance "
                    + "Lex.V3.Contracts.Source.Core.BoundMachineRequest::.ctor, "
                    + "constructor internal instance "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryBinder+MintedBoundMachineRequest::."
                    + "ctor",
                "Lex.V3.Contracts.Source.Core.MachineQueryInputArtifact: by-ref-method public "
                    + "instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationResolvedEvidence::Deconstruc"
                    + "t, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationBoundQuery::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuDocumentFetchBoundQuery::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuObjectFactsBoundQuery::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuWatermarkWitnessBoundQuery::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBoundMachineTuple::Deconstruct, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryInputArtifact::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryInputArtifact::Create, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryInputArtifact::ParseAndVerify",
                "Lex.V3.Contracts.Source.Core.MachineQueryRendererSource: constructor private "
                    + "instance Lex.V3.Contracts.Source.Core.MachineQueryRendererSource::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryRendererSource::Open",
                "Lex.V3.Contracts.Source.Core.OpenedMachineRequest: constructor internal instance "
                    + "Lex.V3.Contracts.Source.Core.OpenedMachineRequest::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryBinder::ReproduceForEvidence, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryBinder::ValidateAndRender, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryBinder::OpenForSend, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.MachineQueryBinder::OpenForSendAsync",
                "Lex.V3.Contracts.Source.Core.RepeatedEnumerationDeliveryReceipt: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationDeliveryReceipt::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryEvidenceSet::TryCompare"
                    + "AndReceipt, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationDeliveryReceipt::TryCreate",
                "Lex.V3.Contracts.Source.Core.RepeatedEnumerationObservationIdentity: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationObservationIdentity::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationObservationIdentity::NewObse"
                    + "rvation",
                "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm: by-ref-method public "
                    + "instance "
                    + "Lex.V3.Contracts.Source.Core.EnumerationDeliveryComparison+CanonicalTupleDoc"
                    + "ument::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRow::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuCellarObjectDecode+ExpressionFactRow::Decon"
                    + "struct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuCellarObjectDecode+ObjectFactRow::Deconstru"
                    + "ct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationFactRow::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationFamilyRow::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationObservedValue::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationSameDateGroup::Deconstruct, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm::.cctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationTerm::RequireCelex, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationTerm::RequireCellarWork, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Core.EnumerationDeliveryComparison::Parse, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Core.EnumerationDeliveryComparison::Pick, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Core.EnumerationDeliveryComparison::Term, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Europe.EuCellarObjectDecode::Term, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm::<Clone>$, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm::BlankNode, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm::Iri, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm::Literal, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationRdfTerm::Unbound, "
                    + "22 compiler-generated",
                "Lex.V3.Contracts.Source.Corpus.VerifiedCorpusRecord: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Corpus.VerifiedCorpusRecord::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Corpus.VerifiedCorpusRecord::ParseAndVerify",
                "Lex.V3.Contracts.Source.Corpus.VerifiedCorpusRecordSet: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Corpus.VerifiedCorpusRecordSet::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Corpus.VerifiedCorpusRecordSet::ParseAndVerify",
                "Lex.V3.Contracts.Source.Europe.EuAuthorityQualifiedToken: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuAuthorityQualifiedToken::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuAuthorityQualifiedToken::Create",
                "Lex.V3.Contracts.Source.Europe.EuBoundaryCrossing: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuBoundaryCrossing::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuBoundaryCrossing::TryCross",
                "Lex.V3.Contracts.Source.Europe.EuCaseLawLinkBinding: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuCaseLawLinkBinding::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuCaseLawLinkBinding::Create",
                "Lex.V3.Contracts.Source.Europe.EuCellarObjectSnapshot: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuCellarObjectSnapshot::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Europe.EuCellarObjectDecode::BuildOneObject, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuCellarObjectDecode::TryDecode, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuCellarObjectSnapshot::TryObserve",
                "Lex.V3.Contracts.Source.Europe.EuConsolidationDiscoveryPlan: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuConsolidationDiscoveryPlan::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationDiscoveryPlan::.cctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationDiscoveryPlan::Create",
                "Lex.V3.Contracts.Source.Europe.EuConsolidationQueryDefinition: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationQueryDefinition::.ctor, "
                    + "method internal instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationDiscoveryPlan::Definition, "
                    + "method private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationDiscoveryPlan::Definition",
                "Lex.V3.Contracts.Source.Europe.EuConsolidationSameDateAssessment: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationSameDateAssessment::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationSameDateAssessment::From",
                "Lex.V3.Contracts.Source.Europe.EuConsolidationSelectedState: by-ref-method public "
                    + "instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationSameDateGroup::Deconstruct, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationSelectedState::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationSelectedState::From, "
                    + "3 compiler-generated",
                "Lex.V3.Contracts.Source.Europe.EuConsolidationSparqlRenderer: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConsolidationSparqlRenderer::.ctor",
                "Lex.V3.Contracts.Source.Europe.EuConstituentClosure: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConstituentClosure::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Europe.EuConstituentClosure::Refuse, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuConstituentClosure::Validate",
                "Lex.V3.Contracts.Source.Europe.EuConstituentStep: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuConstituentStep::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuConstituentStep::Create",
                "Lex.V3.Contracts.Source.Europe.EuDateAxiomBinding: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuDateAxiomBinding::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuDateAxiomBinding::Create",
                "Lex.V3.Contracts.Source.Europe.EuDocumentFetchAddress: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuDocumentFetchAddress::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuDocumentFetchAddress::TryCreate",
                "Lex.V3.Contracts.Source.Europe.EuDocumentFetchOutcome: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuDocumentFetchOutcome::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuDocumentFetchOutcome::Classify",
                "Lex.V3.Contracts.Source.Europe.EuDocumentFetchRenderer: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Europe.EuDocumentFetchRenderer::.ctor",
                "Lex.V3.Contracts.Source.Europe.EuFeedEntryObservation: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuFeedEntryObservation::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuFeedEntryObservation::TryObserve",
                "Lex.V3.Contracts.Source.Europe.EuFeedEntryTermination: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuFeedEntryTermination::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Europe.EuFeedEntryTermination::Resolved, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Europe.EuFeedEntryTermination::Unresolved, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuFeedRootIntersection::Classify",
                "Lex.V3.Contracts.Source.Europe.EuFeedRootIntersection: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuFeedRootIntersection::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Europe.EuFeedRootIntersection::.cctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuFeedRootIntersection::TryBind",
                "Lex.V3.Contracts.Source.Europe.EuFeedTerminalReconciliation: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuFeedTerminalReconciliation::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuFeedTerminalReconciliation::Of",
                "Lex.V3.Contracts.Source.Europe.EuFeedWatermarkEntrySet: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuFeedWatermarkEntrySet::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuFeedWatermarkEntrySet::TryClose",
                "Lex.V3.Contracts.Source.Europe.EuFormexItemSet: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuFormexItemSet::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuFormexItemSet::TryAdmit",
                "Lex.V3.Contracts.Source.Europe.EuFormexPackage: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuFormexPackage::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuFormexPackage::TryAdmit",
                "Lex.V3.Contracts.Source.Europe.EuFormexStreamName: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuFormexStreamName::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Europe.EuFormexStreamName::.cctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuFormexStreamName::TryParse",
                "Lex.V3.Contracts.Source.Europe.EuLegalNoticeEvidence: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuLegalNoticeEvidence::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuLegalNoticeEvidence::FromRoute, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuLegalNoticeEvidence::ParseAndVerify",
                "Lex.V3.Contracts.Source.Europe.EuLegislationSummary: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuLegislationSummary::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuLegislationSummary::Create",
                "Lex.V3.Contracts.Source.Europe.EuLocatedAmendmentAxiom: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuLocatedAmendmentAxiom::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuLocatedAmendmentAxiom::Create",
                "Lex.V3.Contracts.Source.Europe.EuNalSchemeIdentity: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuNalSchemeIdentity::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuNalSchemeIdentity::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Europe.EuNalSchemeIdentity::.cctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Europe.EuNalSchemeIdentity::<Clone>$",
                "Lex.V3.Contracts.Source.Europe.EuObjectFactsDiscoveryPlan: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuObjectFactsDiscoveryPlan::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Europe.EuObjectFactsDiscoveryPlan::.cctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuObjectFactsDiscoveryPlan::Create",
                "Lex.V3.Contracts.Source.Europe.EuObjectFactsQueryDefinition: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Europe.EuObjectFactsQueryDefinition::.ctor, "
                    + "method internal instance "
                    + "Lex.V3.Contracts.Source.Europe.EuObjectFactsDiscoveryPlan::Definition, "
                    + "method private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuObjectFactsDiscoveryPlan::Definition",
                "Lex.V3.Contracts.Source.Europe.EuObjectFactsSparqlRenderer: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Europe.EuObjectFactsSparqlRenderer::.ctor",
                "Lex.V3.Contracts.Source.Europe.EuPrimaryEnumerationRootBinding: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuPrimaryEnumerationRootBinding::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Europe.EuPrimaryEnumerationRootBinding::.cctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuPrimaryEnumerationRootBinding::TryBind",
                "Lex.V3.Contracts.Source.Europe.EuPrimaryEnumerationWitnessReconciliation: "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuPrimaryEnumerationWitnessReconciliation::.c"
                    + "tor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuPrimaryEnumerationWitnessReconciliation::Tr"
                    + "yReconcile",
                "Lex.V3.Contracts.Source.Europe.EuRelationEdgeBinding: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuRelationEdgeBinding::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuRelationEdgeBinding::Create",
                "Lex.V3.Contracts.Source.Europe.EuRepealEdge: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuRepealEdge::.ctor, "
                    + "method public static Lex.V3.Contracts.Source.Europe.EuRepealEdge::Create",
                "Lex.V3.Contracts.Source.Europe.EuRightsMatrix: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuRightsMatrix::.ctor, "
                    + "method public static Lex.V3.Contracts.Source.Europe.EuRightsMatrix::TryAdmit",
                "Lex.V3.Contracts.Source.Europe.EuSelectionRowSet: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuSelectionRowSet::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuSelectionRowSet::TryAdmit",
                "Lex.V3.Contracts.Source.Europe.EuStructuralLocation: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuStructuralLocation::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuStructuralLocation::Parse",
                "Lex.V3.Contracts.Source.Europe.EuTranspositionDeadlineClassification: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuTranspositionDeadlineClassification::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuTranspositionDeadlineClassification::Classi"
                    + "fy",
                "Lex.V3.Contracts.Source.Europe.EuValidityDate: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuValidityDate::.ctor, "
                    + "method public static Lex.V3.Contracts.Source.Europe.EuValidityDate::Create",
                "Lex.V3.Contracts.Source.Europe.EuWatermarkCursor: constructor private instance "
                    + "Lex.V3.Contracts.Source.Europe.EuWatermarkCursor::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuFirstCutWatermarkBootstrap::TryComputeStart"
                    + "Position, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuWatermarkCursor::TryOpen",
                "Lex.V3.Contracts.Source.Europe.EuWatermarkTraversalStep: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuWatermarkTraversalStep::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuWatermarkTraversalStep::TryAdvance",
                "Lex.V3.Contracts.Source.Europe.EuWatermarkWitnessPlan: constructor private "
                    + "instance Lex.V3.Contracts.Source.Europe.EuWatermarkWitnessPlan::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Europe.EuWatermarkWitnessPlan::.cctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Europe.EuWatermarkWitnessPlan::TryFreeze",
                "Lex.V3.Contracts.Source.Europe.EuWatermarkWitnessSparqlRenderer: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Europe.EuWatermarkWitnessSparqlRenderer::.ctor",
                "Lex.V3.Contracts.Source.Http.HeldAcquisitionReceipt: constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.HeldAcquisitionReceipt::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.HeldAcquisitionReceipt::Create, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.HeldAcquisitionReceipt::ParseAndVerify, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.RoutedHttpCanonicalJson::ParseHeldReceipt",
                "Lex.V3.Contracts.Source.Http.HttpLogicalRequest: by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationObservedTransport::Deconstru"
                    + "ct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationResolvedEvidence::Deconstruc"
                    + "t, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.HttpLogicalRequest::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Http.HttpLogicalRequest::.cctor, "
                    + "method public static Lex.V3.Contracts.Source.Http.HttpLogicalRequest::Create, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.HttpLogicalRequest::ParseAndVerify",
                "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome: constructor private "
                    + "instance Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::<Clone>$, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::FromObservedStatu"
                    + "s, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::Gone, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::NotFound, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::Retrieved, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::RetryExhausted, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::RobotsDisallowed, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgDocumentGetOutcome::UnexpectedPublish"
                    + "erStatus",
                "Lex.V3.Contracts.Source.Http.LuxembourgFileUri: constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgFileUri::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgFileUri::RequireValid",
                "Lex.V3.Contracts.Source.Http.LuxembourgFileUriRefusedException: base-constructor "
                    + "protected instance System.ArgumentException::.ctor, "
                    + "base-constructor protected instance System.Exception::.ctor, "
                    + "base-constructor protected instance System.SystemException::.ctor, "
                    + "base-constructor public instance System.ArgumentException::.ctor, "
                    + "base-constructor public instance System.ArgumentException::.ctor, "
                    + "base-constructor public instance System.ArgumentException::.ctor, "
                    + "base-constructor public instance System.ArgumentException::.ctor, "
                    + "base-constructor public instance System.ArgumentException::.ctor, "
                    + "base-constructor public instance System.Exception::.ctor, "
                    + "base-constructor public instance System.Exception::.ctor, "
                    + "base-constructor public instance System.Exception::.ctor, "
                    + "base-constructor public instance System.SystemException::.ctor, "
                    + "base-constructor public instance System.SystemException::.ctor, "
                    + "base-constructor public instance System.SystemException::.ctor, "
                    + "constructor internal instance "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgFileUriRefusedException::.ctor",
                "Lex.V3.Contracts.Source.Http.LuxembourgManifestationSelection: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgManifestationSelection::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgManifestationSelection::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgManifestationSelection::<Clone>$, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.LuxembourgManifestationSelection::Select",
                "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfile: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfile::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfile::.cctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfile::EuropeanUnio"
                    + "nDocumentFetch, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfile::EuropeanUnio"
                    + "nSparql, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfile::LuxembourgDo"
                    + "cumentFetch, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfile::LuxembourgSp"
                    + "arql, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfiles::Resolve, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfiles::ResolveFor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfiles::ResolveFor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfiles::ResolveFor",
                "Lex.V3.Contracts.Source.Http.RepresentationChain: constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.RepresentationChain::.ctor, "
                    + "method public static Lex.V3.Contracts.Source.Http.RepresentationChain::Open",
                "Lex.V3.Contracts.Source.Http.RepresentationChain+AppendedObservation: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Http.RepresentationChain+AppendedObservation::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Http.RepresentationChain::TryAppend",
                "Lex.V3.Contracts.Source.Http.RepresentationChain+FileReplacedEvent: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Http.RepresentationChain+FileReplacedEvent::.ctor",
                "Lex.V3.Contracts.Source.Http.RepresentationChainKey: constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.RepresentationChainKey::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.RepresentationChainKey::Create",
                "Lex.V3.Contracts.Source.Http.RepresentationChainObservation: constructor private "
                    + "instance Lex.V3.Contracts.Source.Http.RepresentationChainObservation::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.RepresentationChainObservation::FromRoute",
                "Lex.V3.Contracts.Source.Http.RobotsPolicyRoute: constructor internal instance "
                    + "Lex.V3.Contracts.Source.Http.RobotsPolicyRoute::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Http.OfficialMachineQuerySourceProfile::EuropeanUnio"
                    + "nRobotsRoute",
                "Lex.V3.Contracts.Source.Http.RobotsPolicyRouteStep: constructor internal instance "
                    + "Lex.V3.Contracts.Source.Http.RobotsPolicyRouteStep::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.RobotsPolicyRouteStep::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Http.RobotsPolicyRouteStep::<Clone>$",
                "Lex.V3.Contracts.Source.Http.RoutedHttpEvidence: by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationObservedTransport::Deconstru"
                    + "ct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Core.RepeatedEnumerationResolvedEvidence::Deconstruc"
                    + "t, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.RoutedHttpEvidence::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.RoutedHttpEvidence::CreateFromVerifiedHops, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.RoutedHttpCanonicalJson::ParseEvidence, "
                    + "method public static Lex.V3.Contracts.Source.Http.RoutedHttpEvidence::Create, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Http.RoutedHttpEvidence::ParseAndVerify",
                "Lex.V3.Contracts.Source.Http.RoutedHttpHop: constructor private instance "
                    + "Lex.V3.Contracts.Source.Http.RoutedHttpHop::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Core.EnumerationDeliveryComparison::TerminalHop, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Http.RoutedHttpCanonicalJson::ParseHop, "
                    + "method public static Lex.V3.Contracts.Source.Http.RoutedHttpHop::Create, "
                    + "1 compiler-generated",
                "Lex.V3.Contracts.Source.Http.RoutedHttpNetworkOrigin: constructor private "
                    + "instance Lex.V3.Contracts.Source.Http.RoutedHttpNetworkOrigin::.ctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Http.RoutedHttpNetworkOrigin::FromUri",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyCandidateResolution: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyCandidateResolution::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyCandidateResolution::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyJoin::ResolveCandidate, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyCandidateResolution::<Clone"
                    + ">$, 1 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyJoinResolution: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyJoinResolution::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyJoinResolution::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyJoinResolution::<Clone>$, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBodyJoin::Resolve, "
                    + "1 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBoundQueryCount: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBoundQueryCount::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::BindCount, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPageBinder::BindCount",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgBoundQueryPage: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Luxembourg.LuxembourgBoundQueryPage::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::BindPage, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPageBinder::Bind",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgConsolidatesShape: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgConsolidatesShape::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgConsolidatesShape::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgScopeResolver::ResolveConsolida"
                    + "tesShape, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgConsolidatesShape::<Clone>$",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryEvidenceSet: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryEvidenceSet::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryEvidenceSet::Materializ"
                    + "eAsync",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryObservation: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryObservation::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryObservation::.cctor, "
                    + "method internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryPass::AllObservations, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryObservation::Create, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryObservation::ForCount, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryObservation::ForPage",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryPass: constructor private "
                    + "instance Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryPass::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryPass::WithPage, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDeliveryPass::BeginWithCount",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDimensionAccounting: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDimensionAccounting::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDimensionAccounting::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgScopeResolver::BuildAccounting, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgDimensionAccounting::<Clone>$",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgLiteralCanonicalization: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgLiteralCanonicalization::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgLiteralCanonicalization::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgLiteralCanonicalizer::Accepted, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgLiteralCanonicalizer::Quarantin"
                    + "e, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgLiteralCanonicalization::<Clone"
                    + ">$, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgLiteralCanonicalizer::Canonical"
                    + "ize",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgPartitionChain: constructor private "
                    + "instance Lex.V3.Contracts.Source.Luxembourg.LuxembourgPartitionChain::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgPartitionChain::SplitLeaf, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgPartitionChain::Root",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgPartitionCover: constructor private "
                    + "instance Lex.V3.Contracts.Source.Luxembourg.LuxembourgPartitionCover::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgPartitionCover::TryCreate",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgPreviousItem: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Luxembourg.LuxembourgPreviousItem::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgPreviousItem::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopology::ResolvePreviousIt"
                    + "ems, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgPreviousItem::<Clone>$",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution+Failed: "
                    + "base-constructor protected instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution::.ctor, "
                    + "constructor internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution+Failed::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution+Failed::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgScopeResolver::Failure, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution+Failed::<Clon"
                    + "e>$",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution+Resolved: "
                    + "base-constructor protected instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution::.ctor, "
                    + "constructor internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution+Resolved::.ct"
                    + "or, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution+Resolved::.ct"
                    + "or, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolution+Resolved::<Cl"
                    + "one>$",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolutionFailure: "
                    + "constructor internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolutionFailure::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolutionFailure::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgScopeResolver::NewFailure, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgScopeResolver::ValidateObservat"
                    + "ion, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgProfileResolutionFailure::<Clon"
                    + "e>$",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan: constructor private "
                    + "instance Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::.cctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::CreateClosed, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::<Clone>$, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::CreateDefaultGraph, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgQueryPlan::ParseAndVerify",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgRelationRule: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Luxembourg.LuxembourgRelationRule::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgRelationRule::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.VerifiedLuxembourgSourceProfile::BuildRel"
                    + "ationRules, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgRelationRule::<Clone>$, "
                    + "1 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResolvedAssertion: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResolvedAssertion::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResolvedAssertion::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgScopeResolver::ResolveAssertion"
                    + "s, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResolvedAssertion::<Clone>$, "
                    + "2 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResolvedRelation: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResolvedRelation::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResolvedRelation::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgScopeResolver::ResolveRelations, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResolvedRelation::<Clone>$, "
                    + "2 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResourceResolution: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResourceResolution::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResourceResolution::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgResourceResolution::<Clone>$, "
                    + "1 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgRightsChannelResolution: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgRightsChannelResolution::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgRightsChannelResolution::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgRightsChannelResolution::<Clone"
                    + ">$, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgRightsChannels::Resolve",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgTypedRoleResolution: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgTypedRoleResolution::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgTypedRoleResolution::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgTypedRoleResolution::.cctor, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgTypedRoleResolution::AcceptedCo"
                    + "nstitutionalReviewDecision, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgTypedRoleResolution::AcceptedCo"
                    + "ordinatedText, "
                    + "method internal static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgTypedRoleResolution::AcceptedCo"
                    + "rrigendum, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgScopeResolver::ResolveTypedRole, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgTypedRoleResolution::<Clone>$, "
                    + "1 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiBlocker: by-ref-method public "
                    + "instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopology+IriObjectEvaluatio"
                    + "n::Deconstruct, "
                    + "by-ref-method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopology+NodeTypeEvaluation"
                    + "::Deconstruct, "
                    + "constructor internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiBlocker::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiBlocker::.ctor, "
                    + "method private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopology::Blocker, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiBlocker::<Clone>$, "
                    + "3 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiCandidate: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiCandidate::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiCandidate::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiCandidate::<Clone>$, "
                    + "1 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopologyResolution: constructor "
                    + "internal instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopologyResolution::.ctor, "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopologyResolution::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopologyResolution::<Clone>"
                    + "$, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.LuxembourgWemiTopology::Resolve, "
                    + "1 compiler-generated",
                "Lex.V3.Contracts.Source.Luxembourg.VerifiedLuxembourgSourceProfile: constructor "
                    + "private instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.VerifiedLuxembourgSourceProfile::.ctor, "
                    + "constructor private static "
                    + "Lex.V3.Contracts.Source.Luxembourg.VerifiedLuxembourgSourceProfile::.cctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Luxembourg.VerifiedLuxembourgSourceProfile::Open",
                "Lex.V3.Contracts.Source.Quarantine.QuarantinePriorCoordinateReproduction: "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Quarantine.QuarantinePriorCoordinateReproduction::.c"
                    + "tor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Quarantine.QuarantinePriorCoordinateReproduction::Tr"
                    + "yCreate",
                "Lex.V3.Contracts.Source.Quarantine.QuarantinedPriorCoordinateInventory: "
                    + "constructor private instance "
                    + "Lex.V3.Contracts.Source.Quarantine.QuarantinedPriorCoordinateInventory::.cto"
                    + "r, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Quarantine.QuarantineInventoryCanonicalizer::VerifyS"
                    + "ignature, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Quarantine.QuarantinedPriorCoordinateInventory::TryR"
                    + "econcile",
                "Lex.V3.Contracts.Source.Scope.ScopeManifestWriteReceipt: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Scope.ScopeManifestWriteReceipt::.ctor, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Scope.ScopeManifestCanonicalWriter::WriteStreaming",
                "Lex.V3.Contracts.Source.Scope.VerifiedScopeManifest: constructor internal "
                    + "instance Lex.V3.Contracts.Source.Scope.VerifiedScopeManifest::.ctor, "
                    + "method public instance "
                    + "Lex.V3.Contracts.Source.Luxembourg.VerifiedLuxembourgSourceProfile::ReduceSc"
                    + "ope, method public static Lex.V3.Contracts.Source.Scope.ScopeReducer::Reduce, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Scope.ScopeReducer::VerifyAndOpen, "
                    + "method public static "
                    + "Lex.V3.Contracts.Source.Scope.VerifiedScopeManifest::ParseAndVerify",
            },
            ClosedSurfaceCensus.GuardedConstruction(CensusScope.SweptHere).ToArray());
    }
}
