<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Lex.Index\Lex.Index.csproj" />
    <ProjectReference Include="..\Lex.Temporal\Lex.Temporal.csproj" />
    <ProjectReference Include="..\Lex.Mcp\Lex.Mcp.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
